"""Renders the Daily Report PDF (§5) from DailyReportDataOut — the exact
same object the Daily Activity screen renders on-screen and prints
(app.reporting.daily.get_daily_report_data), so the PDF can never show
numbers that disagree with what's on screen.
"""
import io
from decimal import Decimal

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from app import schemas


def _fmt_amount(value) -> str:
    if value is None:
        return ""
    return f"{Decimal(value):,.2f}"


def render_daily_report_pdf(data: "schemas.DailyReportDataOut", generated_by: str, generated_at: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=16 * mm, bottomMargin=16 * mm, leftMargin=14 * mm, rightMargin=14 * mm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("ReportTitle", parent=styles["Title"], fontSize=16, spaceAfter=2)
    meta_style = ParagraphStyle("ReportMeta", parent=styles["Normal"], fontSize=9, textColor=colors.grey)
    section_style = ParagraphStyle("SectionHeading", parent=styles["Heading2"], fontSize=12, spaceBefore=12, spaceAfter=4)
    empty_style = ParagraphStyle("EmptySection", parent=styles["Normal"], fontSize=9, textColor=colors.grey)

    story = [
        Paragraph("DOWA Gas Agency — Daily Report", title_style),
        Paragraph(f"Business Date: {data.business_date}", meta_style),
        Paragraph(f"Generated by {generated_by} on {generated_at}", meta_style),
        Spacer(1, 8 * mm),
    ]

    s = data.summary
    summary_rows = [
        ["Sales", _fmt_amount(s.total_sales), "Purchases", _fmt_amount(s.total_purchases)],
        ["Customer Payments", _fmt_amount(s.total_customer_payments), "Plant Payments", _fmt_amount(s.total_plant_payments)],
        ["Investments", _fmt_amount(s.total_investments), "Expenses", _fmt_amount(s.total_expenses)],
        ["Owner Drawings", _fmt_amount(s.total_owner_drawings), "Net Cash Movement", _fmt_amount(s.net_cash_movement)],
        ["Cylinders Out", str(s.total_cylinders_out), "Cylinders In", str(s.total_cylinders_in)],
    ]
    summary_table = Table(summary_rows, colWidths=[45 * mm, 40 * mm, 45 * mm, 40 * mm])
    summary_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("ALIGN", (3, 0), (3, -1), "RIGHT"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(Paragraph("Daily Summary", section_style))
    story.append(summary_table)

    header = ["Date/Time", "ID", "Description", "Customer/Plant", "Reference", "Entered By", "Status", "Amount"]
    for section in data.sections:
        story.append(Paragraph(
            section.label + (f" — Total: {_fmt_amount(section.financial_total)}" if section.financial_total is not None else ""),
            section_style,
        ))
        if not section.rows:
            story.append(Paragraph("No activity for this date.", empty_style))
            continue
        table_rows = [header]
        for r in section.rows:
            table_rows.append([
                r.date.strftime("%H:%M"),
                r.display_id,
                Paragraph(r.description, styles["Normal"]),
                r.customer or r.plant or "",
                r.reference or "",
                r.entered_by,
                r.approval_info or r.status,
                _fmt_amount(r.amount),
            ])
        table = Table(table_rows, colWidths=[16 * mm, 22 * mm, 45 * mm, 30 * mm, 20 * mm, 22 * mm, 22 * mm, 20 * mm], repeatRows=1)
        table.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E2E8F0")),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CBD5E1")),
            ("ALIGN", (-1, 0), (-1, -1), "RIGHT"),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(table)

    doc.build(story)
    return buf.getvalue()
